import { SignatureContextProvider } from '@/lib/context/signature-context';
import { Inter } from 'next/font/google';
import { i18n } from '../../../i18n-config';
import '../../styles/globals.css';

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { lang: string };
}) {
  return (
    <html lang={params.lang}>
      <body className={inter.className}>
        <main>
          <SignatureContextProvider>
            {/*<NavBar />*/}
            {children}
          </SignatureContextProvider>
        </main>
      </body>
    </html>
  );
}
